SID = 'You can find SID in your Twilio Dashboard'

AUTH_TOKEN = 'You can find  on your Twilio Dashboard' 

FROM_NUMBER = 'This is the no. generated by Twilio. You can find this on your Twilio Dashboard'

TO_NUMBER = 'This is your number. Make sure you are adding +91 in beginning'

API_KEY = 'This is your Bolt Cloud accout API key'

DEVICE_ID = 'This is the ID of your Bolt device'
 
MAILGUN_API_KEY = 'This is the private API key which you can find on your Mailgun Dashboard' 

SANDBOX_URL= 'You can find this on your Mailgun Dashboard' 

SENDER_EMAIL = 'test@' + SANDBOX_URL  
# No need to modify this. The sandbox URL is of the format test@YOUR_SANDBOX_URL 

RECIPIENT_EMAIL = 'Enter your Email ID Here' 

API_KEY = 'This is your Bolt Cloud account API key'
 
DEVICE_ID = 'This is the ID of your Bolt device'

bolt_api_key = "XXXX" 
# This is your Bolt Cloud API Key 

device_id = "XXXX" 
# This is the device ID and will be similar to BOLTXXXX where XXXX is some numbers 

telegram_chat_id = "@XXXX" 
# This is the channel ID of the created Telegram channel. Paste after @ symbol. 

telegram_bot_id = "botXXXX" # This is the bot ID of the created Telegram Bot. Paste after bot text.
